[package]
name = "xgbcrew"
version = "0.1.0"
authors = ["Hanna Reitz <hanna@xanclic.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.2"
libc = "0.2.0"
